name: build

on:
  release:
     types:
       - published
env:
  version: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Bump pack.mcmeta version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "**pack.mcmeta"
          find: "{version}"
          replace: "V${{ env.version }}"
      - name: Archive build artifacts
        uses: thedoctor0/zip-release@master
        with:
          filename: "GlowingOreOutlined_v${{ env.version }}.zip"
          exclusions: "*.git* *.yml"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GlowingOreOutlined_v${{ env.version }}
          path: GlowingOreOutlined_v${{ env.version }}.zip