name: release-artifacts

on:
  release:
     types:
       - published
env:
  version: 1.0.0-PRE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Bump pack.mcmeta version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "**pack.mcmeta"
          find: "{version}"
          replace: "V${{ env.version }}"
      - name: Change Directory
        run: cd $(find / -name "conected" -type d)
      - name: Archive Release[Connected Version]
        uses: thedoctor0/zip-release@0.7.1
        with:
          filename: "GlowingOreOutlined-Connected_v${{ env.version }}.zip"
      - name: Change Directory
        run: cd $(find / -name "common" -type d)
      - name: Archive Release[Unconnect Version]
        uses: thedoctor0/zip-release@0.7.1
        with:
          filename: "GlowingOreOutlined_v${{ env.version }}.zip"
      - name: Upload Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}