name: release-artifacts

on:
  release:
     types:
       - published
env:
  version: 1.0.0-PRE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Bump pack.mcmeta version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "**pack.mcmeta"
          find: "{version}"
          replace: "V${{ env.version }}"
#     - name: Archive Release[Connected Version]
#       uses: thedoctor0/zip-release@0.7.1
#       with:
#         directory: "/home/runner/work/GlowingOreOutlined/GlowingOreOutlined/connected"
#         filename: "GlowingOreOutlined-CT_v${{ env.version }}.zip"
      - name: Archive Release[Unconnect Version]
        uses: thedoctor0/zip-release@0.7.1
        with:
          directory: "/home/runner/work/GlowingOreOutlined/GlowingOreOutlined/common"
          filename: "GlowingOreOutlined_v${{ env.version }}.zip"
      - name: Upload Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'GlowingOreOutlined_v${{ env.version }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: GlowingOreOutlined-Connected_v${{ env.version }}
#         path: connected/
#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: GlowingOreOutlined_v${{ env.version }}
#         path: common/